# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LDLT_test <- function(A_) {
    .Call('CppADutils_LDLT_test', PACKAGE = 'CppADutils', A_)
}

LKJ <- function(Y_, eta_, K) {
    .Call('CppADutils_LKJ', PACKAGE = 'CppADutils', Y_, eta_, K)
}

LKJ_unwrap <- function(Y_, K) {
    .Call('CppADutils_LKJ_unwrap', PACKAGE = 'CppADutils', Y_, K)
}

MVN_test <- function(X_, mu_, G_, isPrec) {
    .Call('CppADutils_MVN_test', PACKAGE = 'CppADutils', X_, mu_, G_, isPrec)
}

Sparse_MVN_test <- function(X_, mu_, S_, isPrec) {
    .Call('CppADutils_Sparse_MVN_test', PACKAGE = 'CppADutils', X_, mu_, S_, isPrec)
}

#' @title Inverse logit function
#' @description exp(x)/(1+exp(x))
#' @param X input numeric vector
#' @return exp(x)/(1+exp(x))
invlogit <- function(X) {
    .Call('CppADutils_invlogit', PACKAGE = 'CppADutils', X)
}

#' @title log(1+x)-x
#' @description log(1+x)-x, accurate even for small |x|
#' @param X input numeric vector
#' @return log(1+x)-x
log1pmx <- function(X) {
    .Call('CppADutils_log1pmx', PACKAGE = 'CppADutils', X)
}

#' @title Log inverse logit function
#' @description Log inverse logit, accurate even for very negative x
#' @param X input numeric vector
#' @return p = log(exp(x)/(1+exp(x)) = x-log(1+exp(x))
loginvlogit <- function(X) {
    .Call('CppADutils_loginvlogit', PACKAGE = 'CppADutils', X)
}

#' @title log(1+exp(x))
#' @description log(1+exp(x)), accurate even for very large X.
#' @param X input numeric vector
#' @return log(1+exp(x))
log1pexp <- function(X) {
    .Call('CppADutils_log1pexp', PACKAGE = 'CppADutils', X)
}

#' @title log(gamma(1+x))
#' @description log(gamma(1+x)), accurate even for very small |x|
#' @param X input numeric vector
#' @return log(gamma(1+x))
lgamma1p <- function(X) {
    .Call('CppADutils_lgamma1p', PACKAGE = 'CppADutils', X)
}

#' @title log(gamma(exp(x)))
#' @description log(gamma(exp(x))), accurate even for very small |x|
#' @param X input numeric vector
#' @return log(gamma(exp(x)))
lgammaexp <- function(X) {
    .Call('CppADutils_lgammaexp', PACKAGE = 'CppADutils', X)
}

#' @name CppADutils-tests
#' @title tests
#' @description tests
#' @param X numeric vector (not matrix at this time)
CppADutils_tests <- function(X) {
    invisible(.Call('CppADutils_CppADutils_tests', PACKAGE = 'CppADutils', X))
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_lbeta1 <- function(X) {
    .Call('CppADutils_cppad_lbeta1', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dnorm_log <- function(X) {
    .Call('CppADutils_cppad_dnorm_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dbeta_log <- function(X) {
    .Call('CppADutils_cppad_dbeta_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dlogitbeta_log <- function(X) {
    .Call('CppADutils_cppad_dlogitbeta_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_lgamma1 <- function(X) {
    .Call('CppADutils_cppad_lgamma1', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_lgamma1p <- function(X) {
    .Call('CppADutils_cppad_lgamma1p', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_lgammaexp <- function(X) {
    .Call('CppADutils_cppad_lgammaexp', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_log1p <- function(X) {
    .Call('CppADutils_cppad_log1p', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_expm1 <- function(X) {
    .Call('CppADutils_cppad_expm1', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_log1pexp <- function(X) {
    .Call('CppADutils_cppad_log1pexp', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_log1pmx <- function(X) {
    .Call('CppADutils_cppad_log1pmx', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_loginvlogit <- function(X) {
    .Call('CppADutils_cppad_loginvlogit', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_invlogit <- function(X) {
    .Call('CppADutils_cppad_invlogit', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_incgamma <- function(X) {
    .Call('CppADutils_cppad_incgamma', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_incbeta <- function(X) {
    .Call('CppADutils_cppad_incbeta', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_incbeta2 <- function(X) {
    .Call('CppADutils_cppad_incbeta2', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_lgammaLogExp <- function(X) {
    .Call('CppADutils_cppad_lgammaLogExp', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dt_log <- function(X) {
    .Call('CppADutils_cppad_dt_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dhalft_log <- function(X) {
    .Call('CppADutils_cppad_dhalft_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dhalft_log2 <- function(X) {
    .Call('CppADutils_cppad_dhalft_log2', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dnormTrunc0_log <- function(X) {
    .Call('CppADutils_cppad_dnormTrunc0_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_atan2a <- function(X) {
    .Call('CppADutils_cppad_atan2a', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_atan2b <- function(X) {
    .Call('CppADutils_cppad_atan2b', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_pnorm_log <- function(X) {
    .Call('CppADutils_cppad_pnorm_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_pnorm <- function(X) {
    .Call('CppADutils_cppad_pnorm', PACKAGE = 'CppADutils', X)
}

Wish_test <- function(X_, nu_, S_) {
    .Call('CppADutils_Wish_test', PACKAGE = 'CppADutils', X_, nu_, S_)
}

Inv_Wish_test <- function(X_, nu_, S_) {
    .Call('CppADutils_Inv_Wish_test', PACKAGE = 'CppADutils', X_, nu_, S_)
}

