# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LDLT_test <- function(A_) {
    .Call('_CppADutils_LDLT_test', PACKAGE = 'CppADutils', A_)
}

#' @title LKJ test
#' @param Y_ unconstrained vector
#' @param eta_ parameter >0
#' @param K dimension integer
#' @return List
#' @export
LKJ_test <- function(Y_, eta_, K) {
    .Call('_CppADutils_LKJ_test', PACKAGE = 'CppADutils', Y_, eta_, K)
}

#' @title LKJ constant term in pdf
#' @param eta_ parameter >0
#' @param K dimension integer
#' @return log pdf
#' @export
LKJ_const <- function(eta, K) {
    .Call('_CppADutils_LKJ_const', PACKAGE = 'CppADutils', eta, K)
}

#' @title MVN test
#' @param X_ matrix
#' @param mu_ matrix
#' @param G_ full covariance or precision matrix
#' @param isPrec covariance or precision matrix?
#' @return Numeric vector
#' @export
MVN_test <- function(X_, mu_, G_, isPrec) {
    .Call('_CppADutils_MVN_test', PACKAGE = 'CppADutils', X_, mu_, G_, isPrec)
}

Sparse_MVN_test <- function(X_, mu_, S_, isPrec) {
    .Call('_CppADutils_Sparse_MVN_test', PACKAGE = 'CppADutils', X_, mu_, S_, isPrec)
}

#' @title MatNorm_test
#' @param X_ numeric matrix (k x N)
#' @param M_ numeric matrix (k x N)
#' @param chol_U_ k x k lower triangular matrix of lower triangle of chol(U)
#' @param chol_V_ N x N lower triangular matrix of lower triangle of chol(V)
#' @param isPrec TRUE if U and V are precision matrices.  FALSE is U and V are covariance matrices
#' @return log pdf of matrix normal distribution
MatNorm_test <- function(X_, M_, chol_U_, chol_V_, isPrec) {
    .Call('_CppADutils_MatNorm_test', PACKAGE = 'CppADutils', X_, M_, chol_U_, chol_V_, isPrec)
}

#' @rdname MatNorm_test
#' @param X_ numeric matrix (k x N)
#' @param M_ numeric matrix (k x N)
#' @param U_ k x k dgCMatrix (full, not Cholesky)
#' @param V_ N x N dgCMatrix (full, not Cholesky)
#' @param isPrec TRUE if U and V are precision matrices.  FALSE is U and V are covariance matrices
#' @return log pdf of matrix normal distribution
MatNorm_sparse_test <- function(X_, M_, U_, V_, isPrec) {
    .Call('_CppADutils_MatNorm_sparse_test', PACKAGE = 'CppADutils', X_, M_, U_, V_, isPrec)
}

#' @title CP_erf test
#' @param X_ vector
#' @return Numeric vector
#' @export
CP_erf <- function(X_) {
    .Call('_CppADutils_CP_erf', PACKAGE = 'CppADutils', X_)
}

#' @title MB_erf test
#' @param X_ vector
#' @return Numeric vector
#' @export
MB_erf <- function(X_) {
    .Call('_CppADutils_MB_erf', PACKAGE = 'CppADutils', X_)
}

#' @title gamma_logpdf test
#' @param X_ vector
#' @param R_ vector
#' @param A_ vector
#' @return Numeric vector
#' @export
dgamma_test <- function(X_, R_, A_) {
    .Call('_CppADutils_dgamma_test', PACKAGE = 'CppADutils', X_, R_, A_)
}

#' @name CppADutils-tests
#' @title tests
#' @description tests
#' @param X numeric vector (not matrix at this time)
CppADutils_tests <- function(X) {
    invisible(.Call('_CppADutils_CppADutils_tests', PACKAGE = 'CppADutils', X))
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_lbeta1 <- function(X) {
    .Call('_CppADutils_cppad_lbeta1', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dnorm_log <- function(X) {
    .Call('_CppADutils_cppad_dnorm_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dbeta_log <- function(X) {
    .Call('_CppADutils_cppad_dbeta_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dlogitbeta_log <- function(X) {
    .Call('_CppADutils_cppad_dlogitbeta_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_lgamma1 <- function(X) {
    .Call('_CppADutils_cppad_lgamma1', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_lgamma1p <- function(X) {
    .Call('_CppADutils_cppad_lgamma1p', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_lgammaexp <- function(X) {
    .Call('_CppADutils_cppad_lgammaexp', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_log1p <- function(X) {
    .Call('_CppADutils_cppad_log1p', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_expm1 <- function(X) {
    .Call('_CppADutils_cppad_expm1', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_log1pexp <- function(X) {
    .Call('_CppADutils_cppad_log1pexp', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_log1pmx <- function(X) {
    .Call('_CppADutils_cppad_log1pmx', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_loginvlogit <- function(X) {
    .Call('_CppADutils_cppad_loginvlogit', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_invlogit <- function(X) {
    .Call('_CppADutils_cppad_invlogit', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_incgamma <- function(X) {
    .Call('_CppADutils_cppad_incgamma', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_incbeta <- function(X) {
    .Call('_CppADutils_cppad_incbeta', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_incbeta2 <- function(X) {
    .Call('_CppADutils_cppad_incbeta2', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_lgammaLogExp <- function(X) {
    .Call('_CppADutils_cppad_lgammaLogExp', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dt_log <- function(X) {
    .Call('_CppADutils_cppad_dt_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dhalft_log <- function(X) {
    .Call('_CppADutils_cppad_dhalft_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dhalft_log2 <- function(X) {
    .Call('_CppADutils_cppad_dhalft_log2', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dnormTrunc0_log <- function(X) {
    .Call('_CppADutils_cppad_dnormTrunc0_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_atan2a <- function(X) {
    .Call('_CppADutils_cppad_atan2a', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_atan2b <- function(X) {
    .Call('_CppADutils_cppad_atan2b', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_pnorm_log <- function(X) {
    .Call('_CppADutils_cppad_pnorm_log', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_pnorm <- function(X) {
    .Call('_CppADutils_cppad_pnorm', PACKAGE = 'CppADutils', X)
}

#' @inheritParams CppADutils-tests
#' @rdname CppADutils-tests
cppad_dgamma_log <- function(X) {
    .Call('_CppADutils_cppad_dgamma_log', PACKAGE = 'CppADutils', X)
}

Wish_test <- function(X_, nu_, S_) {
    .Call('_CppADutils_Wish_test', PACKAGE = 'CppADutils', X_, nu_, S_)
}

Inv_Wish_test <- function(X_, nu_, S_) {
    .Call('_CppADutils_Inv_Wish_test', PACKAGE = 'CppADutils', X_, nu_, S_)
}

